# Generated by Django 2.2.5 on 2019-09-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_normalvalue',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_result',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
